name: CI/CD Pipeline for a Node.js Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted

    steps: 
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      
      - name: Run test & store log
        run: |
          mkdir -p test-results
          npm run check > test-results/results.txt || echo "TEST FAILED"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/results.txt

  deploy:
    runs-on: self-hosted
    needs: test

    steps: 
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: show test results
        run: cat results.txt


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g


      - name: Start Application
        run: |
            pm2 kill || true
            pm2 start src/server.js --name "node-app"
            
           

      - name: Show success message
        run: echo "✅ Build Success......"